/*
 * ATTENTION!!! Read this rule before writing action types.
 *
 *  AUTH_                 -> Reducer
 *  _USER_                -> User role
 *  _VERIFY_PHONE_NUMBER_ -> Action
 *  _STARTED              -> Result of action
 */

// USER VERIFY PHONE NUMBER
export const AUTH_USER_VERIFY_PHONE_NUMBER = 'AUTH_USER_VERIFY_PHONE_NUMBER';
export const AUTH_USER_VERIFY_PHONE_NUMBER_STARTED = 'AUTH_USER_VERIFY_PHONE_NUMBER_STARTED';
export const AUTH_USER_VERIFY_PHONE_NUMBER_SUCCEED = 'AUTH_USER_VERIFY_PHONE_NUMBER_SUCCEED';
export const AUTH_USER_VERIFY_PHONE_NUMBER_FAILED = 'AUTH_USER_VERIFY_PHONE_NUMBER_FAILED';

// USER VERIFY SMS CODE
export const AUTH_USER_VERIFY_SMS_CODE = 'AUTH_USER_VERIFY_SMS_CODE';
export const AUTH_USER_VERIFY_SMS_CODE_STARTED = 'AUTH_USER_VERIFY_SMS_CODE_STARTED';
export const AUTH_USER_VERIFY_SMS_CODE_SUCCEED = 'AUTH_USER_VERIFY_SMS_CODE_SUCCEED';
export const AUTH_USER_VERIFY_SMS_CODE_FAILED = 'AUTH_USER_VERIFY_SMS_CODE_FAILED';

// USER REGISTER
export const AUTH_USER_REGISTER = 'AUTH_USER_REGISTER';
export const AUTH_USER_REGISTER_STARTED = 'AUTH_USER_REGISTER_STARTED';
export const AUTH_USER_REGISTER_SUCCEED = 'AUTH_USER_REGISTER_SUCCEED';
export const AUTH_USER_REGISTER_FAILED = 'AUTH_USER_REGISTER_FAILED';

// USER LOGIN
export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN';
export const AUTH_USER_LOGIN_STARTED = 'AUTH_USER_LOGIN_STARTED';
export const AUTH_USER_LOGIN_SUCCEED = 'AUTH_USER_LOGIN_SUCCEED';
export const AUTH_USER_LOGIN_FAILED = 'AUTH_USER_LOGIN_FAILED';
